const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const gitHooksDir = path.join(process.cwd(), '.git', 'hooks');
const preCommitPath = path.join(gitHooksDir, 'pre-commit');
const prePushPath = path.join(gitHooksDir, 'pre-push');

if (!fs.existsSync(path.join(process.cwd(), '.git'))) {
  console.warn('⚠️ No .git directory found. Skipping hook installation.');
  process.exit(0);
}

if (!fs.existsSync(gitHooksDir)) {
  fs.mkdirSync(gitHooksDir, { recursive: true });
}

// 1. Install pre-commit hook
const preCommitContent = `#!/bin/sh
# Git pre-commit hook generated by install-hooks.cjs
node .github/scripts/pre-tool-use.cjs --git-pre-commit
`;
fs.writeFileSync(preCommitPath, preCommitContent, { mode: 0o755 });

// 2. Install pre-push hook
const prePushContent = `#!/bin/sh
# Git pre-push hook generated by install-hooks.cjs
node .github/scripts/pre-tool-use.cjs --git-pre-push "$@"
`;
fs.writeFileSync(prePushPath, prePushContent, { mode: 0o755 });

console.log('✅ Git pre-commit and pre-push hooks installed successfully.');

try {
  if (process.platform !== 'win32') {
    execSync(`chmod +x "${preCommitPath}" "${prePushPath}"`);
  }
} catch (err) {
  console.warn('⚠️ Could not set execute permissions on git hooks:', err.message);
}
