const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const gitHooksDir = path.join(process.cwd(), '.git', 'hooks');
const preCommitPath = path.join(gitHooksDir, 'pre-commit');

if (!fs.existsSync(path.join(process.cwd(), '.git'))) {
  console.warn('⚠️ No .git directory found. Skipping hook installation.');
  process.exit(0);
}

if (!fs.existsSync(gitHooksDir)) {
  fs.mkdirSync(gitHooksDir, { recursive: true });
}

const hookContent = `#!/bin/sh
# Git pre-commit hook generated by install-hooks.cjs
node .github/scripts/pre-tool-use.cjs --git-pre-commit
`;

fs.writeFileSync(preCommitPath, hookContent, { mode: 0o755 });
console.log('✅ Git pre-commit hook installed successfully.');

try {
  if (process.platform !== 'win32') {
    execSync(`chmod +x "${preCommitPath}"`);
  }
} catch (err) {
  console.warn('⚠️ Could not set execute permissions on pre-commit hook:', err.message);
}
