import { DietaryPreferences, EnergyLevel, Ingredient, MealPlanItem, View } from './types';

export const ENERGY_LEVELS = {
  [EnergyLevel.FullPower]: { label: 'Full Power', color: 'bg-energy-full-power', description: 'Ready for a complex recipe!' },
  [EnergyLevel.Cruising]: { label: 'Cruising', color: 'bg-energy-cruising', description: 'Good for standard meal prep.' },
  [EnergyLevel.LowBattery]: { label: 'Low Battery', color: 'bg-energy-low-battery', description: 'Need something quick and easy.' },
  [EnergyLevel.SOS]: { label: 'SOS', color: 'bg-energy-sos', description: '5-minute emergency meals only.' },
};

export const PANTRY_CATEGORIES = [
  'Beverages',
  'Breads & Cereals',
  'Canned Foods & Soups',
  'Coffee & Tea',
  'Dairy, Eggs & Cheese',
  'Frozen Foods',
  'Meat',
  'Oils & Dressings',
  'Pasta, Rice & Beans',
  'Produce',
  'Sauces & Condiments',
  'Snacks & Candy',
  'Spices & Seasonings',
  'Seafood',
  'Baking Items',
  'Personal Care & Health',
  'Others',
];

export const INITIAL_PREFERENCES: DietaryPreferences = {
  globalRestrictions: ['Beef', 'Pork'],
  weeklyCustomizations: [],
  equipment: ['Air Fryer', 'Oven', 'Stovetop', 'Microwave'],
  cuisinePreferences: [],
  shoppingStores: ["Costco", "HEB", "Randall's", "Amazon", "Target", "Indian Store", "Other"],
};

export const INITIAL_PANTRY: Ingredient[] = [
  { id: '1', name: 'Fanta Zero', category: 'Beverages', inStock: false },
  { id: '2', name: 'Mango Nectar', category: 'Beverages', inStock: false },
  { id: '3', name: 'Sprite Zero', category: 'Beverages', inStock: false },
  { id: '4', name: 'Coke Zero', category: 'Beverages', inStock: false },
  { id: '5', name: 'Protein shakes', category: 'Beverages', inStock: true },
  { id: '6', name: 'Parathas', category: 'Breads & Cereals', inStock: false },
  { id: '7', name: 'Bread', category: 'Breads & Cereals', inStock: false },
  { id: '8', name: 'Tortillas', category: 'Breads & Cereals', inStock: false },
  { id: '9', name: 'Burger buns', category: 'Breads & Cereals', inStock: false },
  { id: '10', name: 'Bagels', category: 'Breads & Cereals', inStock: false },
  { id: '11', name: 'Taco shells', category: 'Breads & Cereals', inStock: true },
  { id: '12', name: 'Old fashioned oats', category: 'Breads & Cereals', inStock: true },
  { id: '13', name: 'Gyro pita bread', category: 'Breads & Cereals', inStock: false },
  { id: '14', name: 'Tomato puree', category: 'Canned Foods & Soups', inStock: true },
  { id: '15', name: 'Espresso pods', category: 'Coffee & Tea', inStock: false },
  { id: '16', name: 'Decaf espresso pods', category: 'Coffee & Tea', inStock: false },
  { id: '17', name: 'Cafe bustello (non-instant) powder', category: 'Coffee & Tea', inStock: true },
  { id: '18', name: 'Filter coffee liquid', category: 'Coffee & Tea', inStock: true },
  { id: '19', name: 'K-cup pods', category: 'Coffee & Tea', inStock: true },
  { id: '20', name: 'Eggs', category: 'Dairy, Eggs & Cheese', inStock: false },
  { id: '21', name: 'Milk', category: 'Dairy, Eggs & Cheese', inStock: false },
  { id: '22', name: 'Cheese slices', category: 'Dairy, Eggs & Cheese', inStock: false },
  { id: '23', name: 'Whipped Cream cheese spread', category: 'Dairy, Eggs & Cheese', inStock: false },
  { id: '24', name: 'Cream cheese', category: 'Dairy, Eggs & Cheese', inStock: false },
  { id: '25', name: 'Low-fat cheese', category: 'Dairy, Eggs & Cheese', inStock: false },
  { id: '26', name: 'Queso', category: 'Dairy, Eggs & Cheese', inStock: false },
  { id: '27', name: 'Greek yogurt', category: 'Dairy, Eggs & Cheese', inStock: true },
  { id: '28', name: 'Paneer', category: 'Dairy, Eggs & Cheese', inStock: true },
  { id: '29', name: 'Light butter spread', category: 'Dairy, Eggs & Cheese', inStock: true },
  { id: '30', name: 'Light Sour cream', category: 'Dairy, Eggs & Cheese', inStock: true },
  { id: '31', name: 'Butter sticks', category: 'Dairy, Eggs & Cheese', inStock: true },
  { id: '32', name: 'Frozen peas and carrots', category: 'Frozen Foods', inStock: false },
  { id: '33', name: 'Baby lima beans', category: 'Frozen Foods', inStock: false },
  { id: '34', name: 'Frozen spinach', category: 'Frozen Foods', inStock: false },
  { id: '35', name: 'Black bean burger patties', category: 'Frozen Foods', inStock: false },
  { id: '36', name: 'Frozen turkey burgers', category: 'Frozen Foods', inStock: false },
  { id: '37', name: 'Frozen chicken patties', category: 'Frozen Foods', inStock: false },
  { id: '38', name: 'Frozen chicken lasagna', category: 'Frozen Foods', inStock: false },
  { id: '39', name: 'Frozen harvest blend vegetables', category: 'Frozen Foods', inStock: false },
  { id: '40', name: 'Frozen cauliflower florets', category: 'Frozen Foods', inStock: true },
  { id: '41', name: 'Frozen okra', category: 'Frozen Foods', inStock: true },
  { id: '42', name: 'Frozen popcorn chicken', category: 'Frozen Foods', inStock: true },
  { id: '43', name: 'Frozen broccoli', category: 'Frozen Foods', inStock: true },
  { id: '44', name: 'Frozen mixed vegetables', category: 'Frozen Foods', inStock: true },
  { id: '45', name: 'Frozen green peas', category: 'Frozen Foods', inStock: true },
  { id: '46', name: 'Mix veg paratha', category: 'Frozen Foods', inStock: true },
  { id: '47', name: 'Frozen green beans cut', category: 'Frozen Foods', inStock: true },
  { id: '48', name: 'Eggo waffles', category: 'Frozen Foods', inStock: true },
  { id: '49', name: 'Frozen whole kernel corn', category: 'Frozen Foods', inStock: true },
  { id: '50', name: 'Frozen Chicken Melts', category: 'Frozen Foods', inStock: true },
  { id: '51', name: 'Goat', category: 'Meat', inStock: false },
  { id: '52', name: 'Turkey deli meat', category: 'Meat', inStock: false },
  { id: '53', name: 'Chicken Breasts', category: 'Meat', inStock: true },
  { id: '54', name: 'Lean ground chicken', category: 'Meat', inStock: true },
  { id: '55', name: 'Lean ground turkey', category: 'Meat', inStock: true },
  { id: '56', name: 'Ranch', category: 'Oils & Dressings', inStock: true },
  { id: '57', name: 'Canola Oil', category: 'Oils & Dressings', inStock: true },
  { id: '58', name: 'Light Mayo', category: 'Oils & Dressings', inStock: true },
  { id: '59', name: 'Peanut oil', category: 'Oils & Dressings', inStock: true },
  { id: '60', name: 'Extra Virgin Olive Oil', category: 'Oils & Dressings', inStock: true },
  { id: '61', name: 'Ghee', category: 'Oils & Dressings', inStock: true },
  { id: '62', name: 'Coconut oil', category: 'Oils & Dressings', inStock: true },
  { id: '63', name: 'Distilled White Vinegar (5%)', category: 'Oils & Dressings', inStock: true },
  { id: '64', name: 'Chickpeas', category: 'Pasta, Rice & Beans', inStock: false },
  { id: '65', name: 'Pinto beans', category: 'Pasta, Rice & Beans', inStock: false },
  { id: '66', name: 'Unsalted cashew nuts', category: 'Pasta, Rice & Beans', inStock: false },
  { id: '67', name: 'Toor dal', category: 'Pasta, Rice & Beans', inStock: true },
  { id: '68', name: 'Sona Masoori Rice', category: 'Pasta, Rice & Beans', inStock: true },
  { id: '69', name: 'Black beans', category: 'Pasta, Rice & Beans', inStock: true },
  { id: '70', name: 'Yellow Vatana', category: 'Pasta, Rice & Beans', inStock: true },
  { id: '71', name: 'Quinoa', category: 'Pasta, Rice & Beans', inStock: true },
  { id: '72', name: 'Basmati rice', category: 'Pasta, Rice & Beans', inStock: true },
  { id: '73', name: 'Angel hair pasta', category: 'Pasta, Rice & Beans', inStock: true },
  { id: '74', name: 'Jumbo peanuts', category: 'Pasta, Rice & Beans', inStock: true },
  { id: '75', name: 'Veg Hakka Noodles', category: 'Pasta, Rice & Beans', inStock: true },
  { id: '76', name: 'Cilantro', category: 'Produce', inStock: false },
  { id: '77', name: 'Mint', category: 'Produce', inStock: false },
  { id: '78', name: 'Tomatoes', category: 'Produce', inStock: false },
  { id: '79', name: 'Lemon', category: 'Produce', inStock: false },
  { id: '80', name: 'Lime', category: 'Produce', inStock: false },
  { id: '81', name: 'Red Onions', category: 'Produce', inStock: false },
  { id: '82', name: 'Spinach', category: 'Produce', inStock: false },
  { id: '83', name: 'Serrano peppers', category: 'Produce', inStock: false },
  { id: '84', name: 'Cabbage', category: 'Produce', inStock: false },
  { id: '85', name: 'Bananas', category: 'Produce', inStock: false },
  { id: '86', name: 'Green peppers', category: 'Produce', inStock: false },
  { id: '87', name: 'Carrots', category: 'Produce', inStock: false },
  { id: '88', name: 'Okra', category: 'Produce', inStock: false },
  { id: '89', name: 'Potatoes', category: 'Produce', inStock: false },
  { id: '90', name: 'Green Onions', category: 'Produce', inStock: false },
  { id: '91', name: 'Orange pepper', category: 'Produce', inStock: false },
  { id: '92', name: 'Avocados', category: 'Produce', inStock: false },
  { id: '93', name: 'Garlic', category: 'Produce', inStock: true },
  { id: '94', name: 'Tamarind', category: 'Produce', inStock: true },
  { id: '95', name: 'Shredded Iceberg Lettuce', category: 'Produce', inStock: false },
  { id: '96', name: 'Apples', category: 'Produce', inStock: false },
  { id: '97', name: 'Peanut butter', category: 'Sauces & Condiments', inStock: false },
  { id: '98', name: 'Schezwan chutney', category: 'Sauces & Condiments', inStock: false },
  { id: '99', name: 'Herdez Guacamole Salsa - Medium', category: 'Sauces & Condiments', inStock: false },
  { id: '100', name: 'Hot sauce', category: 'Sauces & Condiments', inStock: false },
  { id: '101', name: 'Soy sauce', category: 'Sauces & Condiments', inStock: true },
  { id: '102', name: 'Roasted Garlic Alfredo Pasta Sauce', category: 'Sauces & Condiments', inStock: true },
  { id: '103', name: 'Hazelnut Chocolate Spread', category: 'Sauces & Condiments', inStock: true },
  { id: '104', name: 'Vanilla Syrup', category: 'Sauces & Condiments', inStock: true },
  { id: '105', name: 'Classic Hazelnut Syrup', category: 'Sauces & Condiments', inStock: true },
  { id: '106', name: 'Sriracha sauce', category: 'Sauces & Condiments', inStock: true },
  { id: '107', name: 'Pizza sauce', category: 'Sauces & Condiments', inStock: true },
  { id: '108', name: 'Chili Garlic sauce', category: 'Sauces & Condiments', inStock: true },
  { id: '109', name: 'Honey', category: 'Sauces & Condiments', inStock: true },
  { id: '110', name: 'Herdez Chipotle Salsa Cremosa', category: 'Sauces & Condiments', inStock: true },
  { id: '111', name: 'Protein bars', category: 'Snacks & Candy', inStock: false },
  { id: '112', name: 'Chips', category: 'Snacks & Candy', inStock: true },
  { id: '113', name: 'Shajeera', category: 'Spices & Seasonings', inStock: false },
  { id: '114', name: 'Brown stevia', category: 'Spices & Seasonings', inStock: false },
  { id: '115', name: 'Curry leaves', category: 'Spices & Seasonings', inStock: false },
  { id: '116', name: 'Rasam powder', category: 'Spices & Seasonings', inStock: true },
  { id: '117', name: 'Coriander powder', category: 'Spices & Seasonings', inStock: true },
  { id: '118', name: 'Salt', category: 'Spices & Seasonings', inStock: true },
  { id: '119', name: 'Turmeric powder', category: 'Spices & Seasonings', inStock: true },
  { id: '120', name: 'Garam masala', category: 'Spices & Seasonings', inStock: true },
  { id: '121', name: 'Everest Tandoori Chicken Masala', category: 'Spices & Seasonings', inStock: true },
  { id: '122', name: 'Everest Pav Bhaji Masala', category: 'Spices & Seasonings', inStock: true },
  { id: '123', name: 'Kashmiri Chili', category: 'Spices & Seasonings', inStock: true },
  { id: '124', name: 'Red Chili', category: 'Spices & Seasonings', inStock: true },
  { id: '125', name: 'Garlic powder', category: 'Spices & Seasonings', inStock: true },
  { id: '126', name: 'Chhole Masala', category: 'Spices & Seasonings', inStock: true },
  { id: '127', name: 'Dried Chives', category: 'Spices & Seasonings', inStock: true },
  { id: '128', name: 'Black peppercorns', category: 'Spices & Seasonings', inStock: true },
  { id: '129', name: 'Hing powder', category: 'Spices & Seasonings', inStock: true },
  { id: '130', name: 'Star anise', category: 'Spices & Seasonings', inStock: true },
  { id: '131', name: 'Dagar phool', category: 'Spices & Seasonings', inStock: true },
  { id: '132', name: 'Mustard seeds', category: 'Spices & Seasonings', inStock: true },
  { id: '133', name: 'Dry coconut shredded', category: 'Spices & Seasonings', inStock: true },
  { id: '134', name: 'Kasoori methi', category: 'Spices & Seasonings', inStock: true },
  { id: '135', name: 'Mace', category: 'Spices & Seasonings', inStock: true },
  { id: '136', name: 'Poppy seeds', category: 'Spices & Seasonings', inStock: true },
  { id: '137', name: 'Sambar powder', category: 'Spices & Seasonings', inStock: true },
  { id: '138', name: 'Cinnamon stick flat', category: 'Spices & Seasonings', inStock: true },
  { id: '139', name: 'Green cardamom', category: 'Spices & Seasonings', inStock: true },
  { id: '140', name: 'Black cardamom', category: 'Spices & Seasonings', inStock: true },
  { id: '141', name: 'Cloves (Whole)', category: 'Spices & Seasonings', inStock: true },
  { id: '142', name: 'Red chili whole', category: 'Spices & Seasonings', inStock: true },
  { id: '143', name: 'Fenugreek seeds', category: 'Spices & Seasonings', inStock: true },
  { id: '144', name: 'Ginger-garlic paste', category: 'Spices & Seasonings', inStock: true },
  { id: '145', name: 'Chowmein Hakka Noodles Masala Spices', category: 'Spices & Seasonings', inStock: true },
  { id: '146', name: 'Rubbed sage', category: 'Spices & Seasonings', inStock: true },
  { id: '147', name: 'Shrimp', category: 'Seafood', inStock: true },
  { id: '148', name: 'Salmon', category: 'Seafood', inStock: true },
  { id: '149', name: 'Pure Vanilla extract', category: 'Baking Items', inStock: true },
  { id: '150', name: 'Cacao powder', category: 'Baking Items', inStock: true },
  { id: '151', name: 'Semi-sweet mini chocolate chips', category: 'Baking Items', inStock: true },
  { id: '152', name: 'Chocolate Jell-O Pudding Powder', category: 'Baking Items', inStock: true },
  { id: '153', name: 'All-purpose flour', category: 'Baking Items', inStock: true },
  { id: '154', name: 'Cornstarch', category: 'Baking Items', inStock: true },
  { id: '155', name: 'Baking soda', category: 'Baking Items', inStock: true },
  { id: '156', name: 'Baking powder', category: 'Baking Items', inStock: true },
  { id: '157', name: 'Whole wheat flour', category: 'Baking Items', inStock: true },
  { id: '158', name: 'Organic plant protein powder', category: 'Personal Care & Health', inStock: true },
  { id: '159', name: 'Red Poha', category: 'Others', inStock: true },
];


export const INITIAL_MEAL_PLAN: MealPlanItem[] = [];

export const NAV_ITEMS = [
  { view: View.Dashboard, label: 'Dashboard', icon: 'home' },
  { view: View.MealPlan, label: 'Meal Plan', icon: 'calendar' },
  { view: View.Cookbook, label: 'My Cookbook', icon: 'book-open' },
  { view: View.Pantry, label: 'Pantry', icon: 'pantry' },
  { view: View.ShoppingList, label: 'Shopping List', icon: 'list' },
  { view: View.FridgeRescue, label: 'Fridge Rescue', icon: 'rescue' },
  { view: View.Preferences, label: 'Preferences', icon: 'settings' },
];